source 'http://rubygems.org'

gem 'rake', '0.8.7'
gem 'rails', '3.0.9'
gem 'mysql2', '~> 0.2.6'
gem 'redis'
gem 'SystemTimer'
gem 'devise'
gem 'json'
gem 'jquery-rails'
gem 'pusher'
gem 'resque'
gem 'multi_json'
gem 'enumerate_it'
gem 'compass'
gem 'sentient_user'
gem 'gravtastic'