question_vote_up: 5
vote_limit: 15
max_credit_per_day: 200
answer_vote_up: 10
question_vote_down: 2
answer_vote_down: 2
answer_vote_down_to_voter: 1
answer_charge: 5
answer_is_accepted: 15
answer_is_accepted_to_acceptor: 2
answer_paid_question: 5


notice_answer_question: "回答了您的问题"
notice_comment_question: "评论了您的问题"
notice_comment_answer: "评论了您的答案"
notice_accept_answer: "接受了您的答案"
notice_follow_user: "关注了您"